### ISSUE TITLE
Counting only CI instead of users

### ISSUE THREAD

**Issue by giordano** [GenieFramework/PkgVizBoard#2]
If I'm reading https://github.com/GenieFramework/PkgVizBoard/blob/fe9d7cad284b2c71c99557f066f3c81e06d56be5/tasks/S3DBTask.jl#L32 correctly you're skipping `"user"` clients and thus only counting CI data, which is not much interesting?  That should probably be `row.client_type != "user"`?

**Comment by AbhimanyuAryan** [comment]
thanks a lot for reporting @giordano it looks like a bug introduced during pre-release code refactoring :)

Will push the fix in couple of hours

**Comment by giordano** [comment]
Fixed by https://github.com/GenieFramework/PkgVizBoard/commit/e54b91677bed3481191cdf9ee86aa9c369ab1433. Thanks!
