### ISSUE TITLE
calculating aggregated download counts

### ISSUE THREAD

**Issue by AbhimanyuAryan** [GenieFramework/PkgVizBoard#3]
As reported by @staticfloat on slack

Also, if these statistics are coming from this [line](https://github.com/GenieFramework/PkgVizBoard/blob/fe9d7cad284b2c71c99557f066f3c81e06d56be5/tasks/S3DBTask.jl#L43) then it is not aggregated across IPs; for that you need to look at `request_addrs`, which is the estimate of the number of unique IPs calculated over that time window.  Using `request_count`, if one IP address downloads it 100 times, you get a value of 100 there.

**Comment by essenciary** [comment]
As discussed on Slack, staying with `request_count` to account for corporate users, educational organisations, etc with multiple users downloading over the same IP.
